## Tensors

- Tensors are a specialized data structure used to encode inputs and outputs of a pytorch model
- Similar to numpy arrays but can run on GPUs

In [1]:
import torch
import numpy as np

### Tensor Initialization

##### Directly from data

In [5]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

##### From a numpy array

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

##### From another tensor

In [7]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8744, 0.9408],
        [0.0222, 0.2345]]) 



##### With random or constant values:

In [8]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5807, 0.5887, 0.8758],
        [0.2193, 0.5650, 0.0461]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Tensor Attributes

In [9]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Tensor Operations

See https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html for tensor operations